# Generated by Django 5.1.6 on 2025-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainova_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
