# Generated by Django 5.1.6 on 2025-02-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainova_api', '0004_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimePasscode',
        ),
    ]
